[build-system]
requires = [
    "setuptools",
    "versioneer[toml]",
    "wheel",
    "numpy~=1.25",
    "Cython~=0.29.36",
]

[tool.cibuildwheel]
test-command = [
    'python -c "import mdtraj"',
]
build = ["cp310-*", "cp311-*", "cp312-*"]
skip = ["*-win32", "*-manylinux_i686", "*-musllinux*"]

[tool.cibuildwheel.linux]
environment-pass = ["CIBW_BUILD"]

[tool.cibuildwheel.macos]
# delocate 0.11.0 has this issue:
# https://github.com/matthew-brett/delocate/issues/229
# https://github.com/matthew-brett/delocate/issues/227
repair-wheel-command = "pip install 'delocate<0.11.0' && delocate-wheel --require-archs {delocate_archs} -w {dest_dir} -v {wheel}"

[tool.versioneer]
VCS = "git"
style = "pep440"
versionfile_source = "mdtraj/_version.py"
versionfile_build = "mdtraj/_version.py"
tag_prefix = ""

[tool.ruff]
line-length=119

[tool.ruff.lint]
select = [
    "F",
    "I",
    "E",
    "W",
    "UP",
    "NPY",
]

[tool.ruff.lint.per-file-ignores]
# Would really, really like to get rid of F403, though F401 is okay
"__init__.py" = ["F401", "F403"]
"tests/test_*.py" = ["NPY002"]
"mdtraj/geometry/__init__.py" = ["F403", "F405"]
"mdtraj/core/trajectory.py" = ["F401"]
"mdtraj/utils/unit/**" = ["F403", "F405"]