[build-system]
requires = [
    "setuptools",
    "wheel",
    # provides the oldest numpy version with wheels on PyPI
    "oldest-supported-numpy",
    "Cython~=0.29.36",
]

[tool.cibuildwheel]
test-command = [
    'python -c "import mdtraj"',
]
build = ["cp38-*", "cp39-*", "cp310-*", "cp311-*", "cp312-*"]
skip = ["*-win32", "*-manylinux_i686", "*-musllinux*"]

[tool.cibuildwheel.linux]
environment-pass = ["CIBW_BUILD"]