name: CI
on:
  push:
    branches:
      - master
      - main
  pull_request:
    branches:
      - master
      - main
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

defaults:
  run:
    shell: bash -l {0}

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false

      matrix:
        os:
          - macOS-latest  # arm64
          - macOS-13  # x86-64
          - ubuntu-latest
          - ubuntu-24.04-arm
        python-version:
          - "3.11"
          - "3.12"
          - "3.13"
          - "3.14.0rc3"

    steps:
    - uses: actions/checkout@v5

    - name: Set up conda environment
      uses: mamba-org/setup-micromamba@v2
      with:
        environment-file: devtools/conda-envs/test.yaml
        create-args: >-
          python=${{ matrix.python-version }}
          conda-forge/label/python_rc::_python_rc

    - name: Install package
      run: |
        python -m pip install .

    - name: Environment Information
      run: |
        micromamba info
        micromamba list

    - name: Run tests
      if: always()
      run: |
        pytest -n logical --durations=10 tests/ -r fE --color=yes
