name: Build and upload to PyPI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build_wheels:
    name: Build wheels for Python ${{ matrix.python }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        python: ["3.9", "3.10", "3.11", "3.12"]
        os: [ubuntu-latest, macos-latest]  # Windows missing zlib
    steps:
      - uses: actions/checkout@v4
      - name: set build type
        run: |
          if [[ "${OSVER}" == "ubuntu-latest" ]]; then
            echo "CIBW_BUILD=cp${PYVER//.}-manylinux_x86_64" >> $GITHUB_ENV
          elif [[ "${OSVER}" == "macos-latest" ]]; then
            # https://cibuildwheel.readthedocs.io/en/stable/faq/#universal2
            echo "CIBW_BUILD=cp${PYVER//.}-macosx_universal2" >> $GITHUB_ENV
          else
            exit 1
          fi
        env:
          PYVER: ${{ matrix.python }}
          OSVER: ${{ matrix.os }}
      - name: Build wheels
        uses: pypa/cibuildwheel@v2.20
        env:
          CIBW_BUILD_VERBOSITY: 1
          CIBW_ARCHS: all
          CIBW_BUILD: ${{ env.CIBW_BUILD }}
      - uses: actions/upload-artifact@v3
        with:
          path: ./wheelhouse/*.whl
  build_sdist:
    name: Build source distribution
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        name: Install Python
        with:
          python-version: '3.12'
      - run: python -m pip install build
      - name: Build sdist
        run: python -m build --sdist

      - uses: actions/upload-artifact@v3
        with:
          path: dist/*.tar.gz

  upload_pypi:
    needs: [build_wheels, build_sdist]
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && startsWith(github.event.ref, 'refs/tags/v')
    permissions:
        # IMPORTANT: this permission is mandatory for trusted publishing
        id-token: write
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: artifact
          path: dist

      - uses: pypa/gh-action-pypi-publish@release/v1
